
# Background
background {
	monitor =
	path = /home/dino/Pictures/wallpapers/wallhaven-2ywd3y.png
	blur_passes = 2
	contrast = 1
}

# General
general {
	hide_cursor = false
}

# Password input
input-field {
	monitor =
	size = 250, 60
	outline_thickness = 2
	dots_size = 0.2
	dots_spacing = 0.35
	dots_center = true
	outer_color = rgba(0, 0, 0, 0)
	inner_color = rgba(0, 0, 0, 0.2)
	position = 0, -200
	halign = center
	valign = center
}

# Date
label {
	monitor =
	text = cmd[update:1000] echo "$(date +"%A, %B %d")"
	color = rgba(242, 243, 244, 0.75)
	font_size = 22
	position = 0, 300
	halign = center
	valign = center
}

# Time
label {
	monitor =
	text = cmd[update:1000] echo "$(date +"%H:%M")"
	color = rgba(242, 243, 244, 0.75)
	font_size = 95
	position = 0, 200
	halign = center
	valign = center
}

